In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
b=np.array([[4],
           [-1],
           [6]])
b

array([[ 4],
       [-1],
       [ 6]])

In [4]:
C=np.array([[3,-2],
           [7,1]])
C

array([[ 3, -2],
       [ 7,  1]])

In [6]:
D=np.array([[3,-2,0,1],
           [7,1,-1,2],
           [4,-1,1,3]])
D

array([[ 3, -2,  0,  1],
       [ 7,  1, -1,  2],
       [ 4, -1,  1,  3]])

In [7]:
a=np.zeros((1,2))
a

array([[0., 0.]])

In [8]:
np.ones((4,1))

array([[1.],
       [1.],
       [1.],
       [1.]])